# Generated by Django 3.2.16 on 2024-03-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_auto_20240303_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='output_order',
            field=models.PositiveSmallIntegerField(default=100, help_text='Порядок отображения. По умолчанию 100.Чем ниже значение, тем выше будет отображаться.', verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='output_order',
            field=models.PositiveSmallIntegerField(default=100, help_text='Порядок отображения. По умолчанию 100.Чем ниже значение, тем выше будет отображаться.', verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Slug - это сокращенная метка для чего - либо, содержащая только латинские буквы, цифры, подчеркивания или дефисы.', max_length=64, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Уникальное название, не более 256 символов', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='is_on_main',
            field=models.BooleanField(default=False, help_text='Чтобы отображалось на главной странице поставь галочку', verbose_name='На главную'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='title',
            field=models.CharField(help_text='Уникальное название, не более 256 символов', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='slug',
            field=models.SlugField(help_text='Slug - это сокращенная метка для чего - либо, содержащая только латинские буквы, цифры, подчеркивания или дефисы.', max_length=64, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='title',
            field=models.CharField(help_text='Уникальное название, не более 256 символов', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='wrapper',
            name='title',
            field=models.CharField(help_text='Уникальное название, не более 256 символов', max_length=256, verbose_name='Название'),
        ),
    ]
